#!/usr/bin/env python3
"""Render retained real M28 connector evidence with production UI components."""

from __future__ import annotations

import os
import stat
from collections.abc import Mapping
from pathlib import Path
from typing import Final

import streamlit as st

from schemabridge.adapters.workflows.system import SystemWorkflowClock
from schemabridge.application.authorization import DenyByDefaultAuthorizationPolicy
from schemabridge.application.ui_workflow import UiCapabilities
from schemabridge.bootstrap import build_streamlit_principal
from schemabridge.config import Settings
from schemabridge.domain.identity import (
    AuthenticatedPrincipal,
    AuthenticationMethod,
    IdentityRole,
    WorkflowPermission,
)
from schemabridge.entrypoints.streamlit.components import (
    PageActionKind,
    inject_styles,
    render_header,
    render_modes,
    render_query_studio,
)
from schemabridge.entrypoints.streamlit.connector_acceptance import (
    M28_BROWSER_RELEASE_REF,
    M28_BROWSER_SCENARIO_ENV,
    M28_BROWSER_SCENARIO_LABELS,
    M28_BROWSER_STATE_FILE_ENV,
    M28BrowserAcceptanceState,
    M28BrowserScenario,
    build_m28_browser_view,
    is_m28_private_environment_key,
)

_MAX_STATE_BYTES: Final = 256 * 1024
_EXECUTED_KEY: Final = "_m28_browser_executed_scenarios"


def main() -> None:
    """Load one public evidence file and delegate rendering to Query Studio."""

    st.set_page_config(
        page_title="SchemaBridge · M28 connector acceptance",
        page_icon="🌉",
        layout="wide",
        initial_sidebar_state="collapsed",
    )
    inject_styles()
    _inject_mobile_styles()
    try:
        state, initial = _load_configuration(os.environ)
        principal = _build_acceptance_principal()
        capabilities = _capabilities(principal)
        if (
            not capabilities.can_view
            or not capabilities.can_execute
            or not capabilities.can_view_result
        ):
            raise ValueError("M28 browser principal lacks required acceptance permissions")
    except (OSError, ValueError):
        st.error("m28_browser_state_invalid: Acceptance evidence was rejected.")
        st.caption("No connector, source, route, or credential was opened.")
        st.stop()

    _render_principal_summary(principal)
    options = tuple(M28BrowserScenario)
    selected = st.selectbox(
        "Closed M28 acceptance scenario",
        options,
        index=options.index(initial),
        format_func=lambda item: M28_BROWSER_SCENARIO_LABELS[item],
        key="m28-browser-scenario",
    )
    executed = _executed_scenarios()
    view = build_m28_browser_view(
        state,
        selected,
        executed=selected.value in executed,
    )

    render_header(view)
    render_modes(view.modes)
    st.info(
        "Acceptance presentation uses retained, aggregate-only evidence generated by the "
        "real target-bound compiler, independent AST guard, routed PostgreSQL preflight, "
        "and read-only preview. The browser process has no connector credential."
    )
    st.caption(
        "Evidence fingerprint "
        f"{state.evidence_fingerprint[:12]}… · real preflights "
        f"{state.real_preflight_calls} · real previews {state.real_preview_calls}."
    )
    st.markdown("#### Escaped hostile metadata probe")
    st.write(state.hostile_metadata)
    st.caption(
        "The literal metadata above must remain text; it must not create a script element "
        "or set `window.__m28_xss`."
    )
    st.divider()

    action = render_query_studio(view, capabilities)
    if action is not None:
        if action.kind is not PageActionKind.APPROVE_EXECUTION:
            st.error("m28_browser_action_invalid: The acceptance action was rejected.")
            st.stop()
        if not view.query or not view.query.can_execute:
            st.error("m28_browser_execution_blocked: No executable checkpoint exists.")
            st.stop()
        executed.add(selected.value)
        st.session_state[_EXECUTED_KEY] = sorted(executed)
        st.rerun()


def _load_configuration(
    environment: Mapping[str, str],
) -> tuple[M28BrowserAcceptanceState, M28BrowserScenario]:
    required = {
        "SCHEMABRIDGE_ENVIRONMENT": "development",
        "SCHEMABRIDGE_AUTH_MODE": "local-demo",
        "SCHEMABRIDGE_RELEASE_REF": M28_BROWSER_RELEASE_REF,
    }
    if any(environment.get(key) != value for key, value in required.items()):
        raise ValueError("M28 browser app requires the isolated acceptance profile")
    if any(value and is_m28_private_environment_key(key) for key, value in environment.items()):
        raise ValueError("M28 browser app process contains a forbidden capability")
    raw_path = environment.get(M28_BROWSER_STATE_FILE_ENV)
    raw_scenario = environment.get(M28_BROWSER_SCENARIO_ENV)
    if raw_path is None or raw_scenario is None:
        raise ValueError("M28 browser app configuration is incomplete")
    try:
        scenario = M28BrowserScenario(raw_scenario)
    except ValueError as error:
        raise ValueError("M28 browser scenario is outside the closed allowlist") from error
    return _read_public_state(Path(raw_path)), scenario


def _build_acceptance_principal() -> AuthenticatedPrincipal:
    """Compose the real local-demo identity boundary without reading ambient settings."""

    settings = Settings.model_validate(
        {
            "environment": "development",
            "auth_mode": "local-demo",
            "local_workspace": "m28-browser-acceptance",
            "local_subject": "browser-operator",
            "local_roles": ("analyst",),
        }
    )
    principal = build_streamlit_principal(settings=settings)
    if (
        principal.authentication_method is not AuthenticationMethod.LOCAL_DEMO
        or principal.roles != frozenset({IdentityRole.ANALYST})
        or not principal.workspace_id.startswith("sb_workspace_v1_")
        or not principal.actor_id.startswith("sb_actor_v1_")
    ):
        raise ValueError("M28 browser principal is invalid")
    return principal


def _render_principal_summary(principal: AuthenticatedPrincipal) -> None:
    st.markdown("#### Authenticated principal")
    st.caption(f"Method · {principal.authentication_method.value}")
    st.caption(f"Principal · …{principal.actor_id[-12:]}")
    st.caption(f"Workspace · …{principal.workspace_id[-12:]}")
    st.caption("Roles · analyst")


def _read_public_state(path: Path) -> M28BrowserAcceptanceState:
    if not path.is_absolute() or ".." in path.parts:
        raise ValueError("M28 browser state path is invalid")
    flags = os.O_RDONLY
    if hasattr(os, "O_CLOEXEC"):
        flags |= os.O_CLOEXEC
    if hasattr(os, "O_NOFOLLOW"):
        flags |= os.O_NOFOLLOW
    descriptor: int | None = None
    try:
        before = path.lstat()
        if (
            not stat.S_ISREG(before.st_mode)
            or stat.S_IMODE(before.st_mode) != 0o600
            or before.st_uid != os.geteuid()
            or not 0 < before.st_size <= _MAX_STATE_BYTES
        ):
            raise OSError
        descriptor = os.open(path, flags)
        opened = os.fstat(descriptor)
        if (
            opened.st_dev != before.st_dev
            or opened.st_ino != before.st_ino
            or stat.S_IMODE(opened.st_mode) != 0o600
            or opened.st_uid != os.geteuid()
            or opened.st_size != before.st_size
        ):
            raise OSError
        chunks: list[bytes] = []
        remaining = opened.st_size
        while remaining:
            chunk = os.read(descriptor, min(remaining, 64 * 1024))
            if not chunk:
                raise OSError
            chunks.append(chunk)
            remaining -= len(chunk)
        if os.read(descriptor, 1):
            raise OSError
        after = os.fstat(descriptor)
        if (
            after.st_dev != opened.st_dev
            or after.st_ino != opened.st_ino
            or after.st_size != opened.st_size
            or after.st_mtime_ns != opened.st_mtime_ns
        ):
            raise OSError
        return M28BrowserAcceptanceState.from_json(b"".join(chunks))
    finally:
        if descriptor is not None:
            os.close(descriptor)


def _executed_scenarios() -> set[str]:
    raw = st.session_state.get(_EXECUTED_KEY, ())
    if not isinstance(raw, list | tuple) or any(
        not isinstance(item, str)
        or item
        not in {
            M28BrowserScenario.TENANT_A_ACCEPTED.value,
            M28BrowserScenario.TENANT_B_ACCEPTED.value,
        }
        for item in raw
    ):
        st.session_state.pop(_EXECUTED_KEY, None)
        return set()
    return set(raw)


def _capabilities(principal: AuthenticatedPrincipal) -> UiCapabilities:
    permissions = DenyByDefaultAuthorizationPolicy().permissions_for(
        principal,
        at=SystemWorkflowClock().now(),
    )
    return UiCapabilities(
        can_view=WorkflowPermission.VIEW in permissions,
        can_create=False,
        can_confirm=False,
        can_execute=WorkflowPermission.EXECUTE in permissions,
        can_publish=False,
        can_skip=False,
        can_retry=False,
        can_view_result=WorkflowPermission.VIEW_RESULT in permissions,
        can_export=False,
    )


def _inject_mobile_styles() -> None:
    st.markdown(
        """
        <style>
        .stApp, [data-testid="stAppViewContainer"], [data-testid="stMain"] {
            max-width:100%; overflow-x:hidden;
        }
        [data-testid="stMetric"], code, pre, p, span, div {
            overflow-wrap:anywhere;
        }
        @media (max-width: 640px) {
            [data-testid="stHorizontalBlock"] { flex-wrap:wrap; }
            [data-testid="column"] {
                min-width:0 !important;
                width:100% !important;
                flex:1 1 100% !important;
            }
        }
        </style>
        """,
        unsafe_allow_html=True,
    )


if __name__ == "__main__":
    main()
